### PR TITLE
Added some missing item identifiers for loot tables & trades.

### PR DESCRIPTION
**Pull request by StealthyExpertX**
Added some missing item identifiers.

Added missing legacy item string ids.

minecraft:muttonraw
minecraft:map
minecraft:emptymap
minecraft:nametag
minecraft:fireball
minecraft:speckled_melon
minecraft:horsearmorgold

These are found in the /data folder of Minecraft between versions "vanilla" to "vanilla_1.19.70"

### CODE REVIEW

**Review by DaanV2 — CHANGES_REQUESTED** [review]
I'm hesitant to add these. Vanilla files are not perse correct. And I know some of these are legacy items, and I don't want to support these since /give might not work for them.

So Ill check them with the give comment and see which are usable

**Comment by DaanV2** [comment]
I have checked this items in minecraft, and while it still works they are apparently legacy items and no longer supported or suggested to be used. As this might change in the future, so for now Ill be closing this PR 🙂

**Comment by StealthyExpertX** [comment]
The reason, I mentioned these items is because they are found in loot tables and trade tables in the current vanilla pack.

**Comment by DaanV2** [comment]
I know 🙂 
But I don't consider the vanilla packs as 100% correct, I have seen a lot of mistakes. I cant justify supporting those legacy Minecraft items if in the future they are deprecated.

**Pull request closed without merging**
